### ISSUE TITLE
WIKI

### ISSUE THREAD

**Issue by electron64** [MarwanAlaa94/Donation-platform#16]
Hello , i want to try your app , can you please give some infos about settings and how install it please?

**Comment by Ahmed-elsayed-mahmoud** [comment]
@electron64  
Kindly, follow these instructions to run the app and to know more information about it
[ReadMe](https://github.com/Ahmed-elsayed-mahmoud/Donation-Platform/blob/master/README.md)

**Comment by electron64** [comment]
Hello thank you very much for the info.
I tried to install it but i still get an error when i run rake db:migrate .

`rake db:migrate
rake aborted!
NameError: uninitialized constant Rack::Session::Abstract::Persisted
/var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/session/abstract_store.rb:90:in `<module:Session>'
/var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/session/abstract_store.rb:8:in `<module:ActionDispatch>'
/var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/session/abstract_store.rb:7:in `<top (required)>'
/var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/session/cookie_store.rb:2:in `<top (required)>'
/var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application/configuration.rb:181:in `const_get'
/var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application/configuration.rb:181:in `session_store'
/var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application/default_middleware_stack.rb:58:in `block in build_stack'
/var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application/default_middleware_stack.rb:13:in `tap'
/var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application/default_middleware_stack.rb:13:in `build_stack'
/var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application.rb:504:in `default_middleware_stack'
/var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:506:in `block in app'
/var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:504:in `synchronize'
/var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:504:in `app'
/var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application/finisher.rb:37:in `block in <module:Finisher>'
/var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application.rb:352:in `initialize!'
/root/Donation-Platform/config/environment.rb:5:in `<top (required)>'
/var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application.rb:328:in `require_environment!'
/var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application.rb:448:in `block in run_tasks_blocks'
/var/lib/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)`

**Comment by electron64** [comment]
Thank you.
Sorry for my late answer.
